Traceback (most recent call last):
  File "c:\Users\jojac\Documents\QuantumErrorCorrection\decoder\test.py", line 15, in <module>
    d.train()
  File "c:\Users\jojac\Documents\QuantumErrorCorrection\decoder\decoder.py", line 295, in train
    loss = loss_fun(out, flips)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jojac\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jojac\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jojac\anaconda3\Lib\site-packages\torch\nn\modules\loss.py", line 821, in forward
    return F.binary_cross_entropy_with_logits(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jojac\anaconda3\Lib\site-packages\torch\nn\functional.py", line 3639, in binary_cross_entropy_with_logits
    raise ValueError(
ValueError: Target size (torch.Size([10, 1])) must be the same as input size (torch.Size([10, 12]))
